
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).parent))

from util.baseline_manager import BaselineManager

def main():
    # Use the data generated by verify_import.py
    data_path = "data_verify/latest_frontend_lineage.json"
    baseline_path = "tests/baseline_snapshot.json"
    
    print(f"Comparing {data_path} against {baseline_path}...")
    
    manager = BaselineManager(data_path=data_path, baseline_path=baseline_path)
    success = manager.verify_against_snapshot()
    
    if success:
        sys.exit(0)
    else:
        sys.exit(1)

if __name__ == "__main__":
    main()
