CREATE TABLE CONSUMPTION_PRIMA.HrDepartments
(
	[DEPARTMENT_ID] [int] NULL,
	[DEPARTMENT] [varchar](100) NULL,
	[DEPARTMENT_LOC] [nvarchar](200) NULL,
	[DEPARTMENT_SHORT_NAME] [varchar](40) NULL,
	[DEPARTMENT_SEQUENCE] [int] NULL,
	[CREATED_BY] [varchar](50) NULL,
	[CREATED_AT] [datetime] NULL,
	[UPDATED_BY] [varchar](50) NULL,
	[UPDATED_AT] [datetime] NULL,
	[RECORD_ACTIVE] [bit] NULL,
	[IS_GROUP] [bit] NULL,
	[PARENT_ID] [int] NULL,
	[ROWVERSION] [varchar](50) NULL,
	[DIVISION_ID] [int] NULL,
	[IS_OPERATIONS] [bit] NULL,
	[DIVISION_CODE] [varchar](5) NULL,
	[SKILL_MATRIX_START_DATE] [date] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
