CREATE TABLE [CONSUMPTION_PRIMAREPORTING].[ProjectMilestones]
(
	[Project Code] [VARCHAR](20) NULL,
	[Project Name] [VARCHAR](255) NULL,
	[Country ID] [INT] NULL,
	[Country] [VARCHAR](100) NULL,
	[Milestone Name] [VARCHAR](302) NULL,
	[Milestone Current Value] [INT] NULL,
	[Is Contractual] [BIT] NULL,
	[Non PSI] [BIT] NULL,
	[Is Custom] [BIT] NULL,
	[Target Value] [INT] NULL,
	[Sequence] [INT] NULL,
	[Project Milestone Group Identity] [VARCHAR](50) NULL,
	[Project Milestone Status] [NVARCHAR](200) NULL,
	[Project Milestone Type] [NVARCHAR](200) NULL,
	[First Site Identified Planned Date] [DATE] NULL,
	[First Site Identified Forecast Date] [DATE] NULL,
	[First Site Identified Actual Date] [DATE] NULL,
	[Last Site Identified Planned Date] [DATE] NULL,
	[Last Site Identified Forecast Date] [DATE] NULL,
	[Last Site Identified Actual Date] [DATE] NULL,
	[First Site Selected Planned Date] [DATE] NULL,
	[First Site Selected Forecast Date] [DATE] NULL,
	[First Site Selected Actual Date] [DATE] NULL,
	[Last Site Selected Planned Date] [DATE] NULL,
	[Last Site Selected Forecast Date] [DATE] NULL,
	[Last Site Selected Actual Date] [DATE] NULL,
	[First Site Evaluated Planned Date] [DATE] NULL,
	[First Site Evaluated Forecast Date] [DATE] NULL,
	[First Site Evaluated Actual Date] [DATE] NULL,
	[Last Site Evaluated Planned Date] [DATE] NULL,
	[Last Site Evaluated Forecast Date] [DATE] NULL,
	[Last Site Evaluated Actual Date] [DATE] NULL,
	[First Site Closed Planned Date] [DATE] NULL,
	[First Site Closed Forecast Date] [DATE] NULL,
	[First Site Closed Actual Date] [DATE] NULL,
	[Last Site Closed Planned Date] [DATE] NULL,
	[Last Site Closed Forecast Date] [DATE] NULL,
	[Last Site Closed Actual Date] [DATE] NULL,
	[Last Monitoring Visit Completed Planned Date] [DATE] NULL,
	[Last Monitoring Visit Completed Forecast Date] [DATE] NULL,
	[Last Monitoring Visit Completed Actual Date] [DATE] NULL,
	[First Patient In Planned Date] [DATE] NULL,
	[First Patient In Forecast Date] [DATE] NULL,
	[First Patient In Actual Date] [DATE] NULL,
	[Last Patient In Planned Date] [DATE] NULL,
	[Last Patient In Forecast Date] [DATE] NULL,
	[Last Patient In Actual Date] [DATE] NULL,
	[Last Patient Out Planned Date] [DATE] NULL,
	[Last Patient Out Forecast Date] [DATE] NULL,
	[Last Patient Out Actual Date] [DATE] NULL,
	[Planned Date] [DATE] NULL,
	[Forecast Date] [DATE] NULL,
	[Actual Date] [DATE] NULL,
	[Region ID] [INT] NULL,
	[Src Created Date] [DATETIME] NULL,
	[Src Updated Date] [DATETIME] NULL,
	[Planned Enrollment (Months)] [INT] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO