CREATE TABLE [CONSUMPTION_FINANCE].[FactGLSAP] (
    [FactGLSAPKey]              BIGINT           IDENTITY (1, 1) NOT NULL,
    [CompanyKey]                INT              NULL,
    [DepartmentKey]             INT              NULL,
    [MonthFinanceKey]           INT              NULL,
    [CurrencyKey]               INT              NULL,
    [AccountDetailsSAPKey]      INT              NULL,
    [Client]                    NVARCHAR (3)     NULL,
    [Type]                      VARCHAR (3)      NULL,
    [Periode]                   VARCHAR (6)      NULL,
    [PeriodName]                VARCHAR (5)      NULL,
    [PeriodDescription]         VARCHAR (50)     NULL,
    [Year]                      VARCHAR (4)      NULL,
    [Month]                     VARCHAR (2)      NULL,
    [CompanyCode]               NVARCHAR (4)     NULL,
    [GLAccountNumber]           NVARCHAR (10)    NULL,
    [GLAccountNumberShort]      NVARCHAR (20)    NULL,
    [GroupAccountNumber]        NVARCHAR (12)    NULL,
    [BusinessArea]              NVARCHAR (4)     NULL,
    [CompanyIDofTradingPartner] NVARCHAR (6)     NULL,
    [CostCenter]                NVARCHAR (10)    NULL,
    [Department]                NVARCHAR (12)    NULL,
    [DIM3CurrForCognos]         NVARCHAR (5)     NULL,
    [Currency]                  NVARCHAR (5)     NULL,
    [Amount]                    DECIMAL (38, 18) NULL,
    [CreatedBy]                 VARCHAR (100)    NOT NULL,
    [UpdatedBy]                 VARCHAR (100)    NOT NULL,
    [CreatedAt]                 DATETIME         NOT NULL,
    [UpdatedAt]                 DATETIME         NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

