CREATE TABLE [CONSUMPTION_PRIMAREPORTING].[SiteEvents]
(
	[Project Code] [varchar](20) NULL,
	[Project Name] [varchar](255) NULL,
	[Country ID] [int] NULL,
	[Country] [varchar](100) NULL,
	[Site ID] [int] NULL,
	[Site Name] [varchar](500) NULL,
	[Site Name 2] [varchar](255) NULL,
	[PI Name] [nvarchar](204) NULL,
	[Site Status] [nvarchar](200) NULL,
	[Monitor] [varchar](102) NULL,
	[Event Name] [varchar](8000) NULL,
	[Seq. #] [int] NULL,
	[Unblinded] [varchar](3) NULL,
	[Initial Forecast] [datetime] NULL,
	[Forecast Date] [date] NULL,
	[Actual Date] [datetime] NULL,
	[Days on Site] [real] NULL,
	[Remote Visit] [varchar](3) NULL,
	[Draft Submitted] [datetime] NULL,
	[Days To Draft] [int] NULL,
	[First Review] [datetime] NULL,
	[Second Review] [datetime] NULL,
	[Due Final] [date] NULL,
	[Final Report] [datetime] NULL,
	[Days To Final] [int] NULL,
	[Sent To Client] [datetime] NULL,
	[Pre-Visit Letter] [datetime] NULL,
	[Follow-Up Letter] [datetime] NULL,
	[Days to Follow-Up Letter] [int] NULL,
	[Approved By Client] [datetime] NULL,
	[Attendees Id] [varchar](1000) NULL,
	[Attendees] [varchar](8000) NULL,
	[PSI Attended Visit] [int] NULL,
	[Psi Contact] [varchar](102) NULL,
	[Site Contact] [varchar](102) NULL,
	[Comments] [varchar](max) NULL,
	[Covid 19 Related] [varchar](3) NULL,
	[Planned Date] [datetime] NULL,
	[No Report Flag] [bit] NULL,
	[Is Last Routine Visit] [bit] NULL,
	[Visit Object] [nvarchar](200) NULL,
	[Resubmission Date] [date] NULL,
	[Days After Previous Visit] [int] NULL,
	[SrcCreatedDate] [datetime] NULL,
	[SrcUpdatedDate] [datetime] NULL,
	[Reporting Site ID] [varchar](255) NULL,
	[SITE_EVENT_ID] [int] NULL,
	[# Attendees (Routine visits)] [int] NULL,
	[Total days on-site] [real] NULL,
	[Previous visit date] [datetime] NULL,
	[Days since previous visit] [int] NULL,
	[Additional Purpose] [varchar](8000) NULL,
	[Field Training] [varchar](3) NULL,
	[Report Finalized Late] [varchar](3) NULL,
	[Report Overdue] [varchar](3) NULL,
	[Days since previous visit (Business Days)] [int] NULL,
	[WORK_DAYS_AFTER_PREVIOUS_VISIT] [int] NULL,
	[PREVIOUS_VISIT_ID] [int] NULL,
	[SATELLITE_SITES_LIST] [varchar](max) NULL,
	[SOURCE_ESSENCE] [varchar](30) NULL,
	[SOURCE_OBJECT_ID] [int] NULL,
	[DURATION_TOTAL] [int] NULL,
	[DURATION_BY_DAY] [varchar](max) NULL,
	[IS_COMONITORING_VISIT] [bit] NULL,
	[COMONITORING_OUTCOME_ID] [int] NULL,
	[DUE_TO_FORCE_MAJEURE_FLAG] [bit] NULL,
	[ADDITIONAL_MONITORS_LIST] [varchar](100) NULL,
	[SUPERVISING_QC_COMONITORS_LIST] [varchar](100) NULL,
	[FIELD_ASSESSORS_LIST] [varchar](200) NULL,
	[FIELD_TRAINERS_LIST] [varchar](200) NULL,
	[TRAINEES_LIST] [varchar](200) NULL,
	[OTHER_PARTICIPANTS_LIST] [varchar](100) NULL,
	[REVIEWER_ID] [int] NULL,
	[PRIMARY_MONITOR_ID] [int] NULL,
	[VENDOR_MONITOR_ID] [int] NULL,
	[ORIGINATOR_ID] [int] NULL,
	[VISIT_TYPE] [varchar](200) NULL,
	[RMV Event Name] [varchar](212) NULL,
	[DUE_DATE_TO_DRAFT] [date] NULL,
	[DAYS_ON_SITE_PLANNED] [real] NULL,
	[DRAFT_OVERDUE_DAYS] [int] NULL,
	[FINAL_OVERDUE_DAYS] [int] NULL,
	[FU_OVERDUE_DAYS] [int] NULL,
	[SENT_TO_CLIENT_OVERDUE_DAYS] [int] NULL,
	[SUPERVISING_MONITORS_LIST] [varchar](200) NULL,
	[CUSTOM_VISIT_PURPOSE] [varchar](1000) NULL,
	[ACTUAL_DATE_ENTERED_DATE] [datetime] NULL,
	[IS_MULTIPLE_PLANNED_DAYS_FLAG] [bit] NULL,
	[DURATION_BY_DAY_PLANNED] [varchar](max) NULL,
	[SUBJECTS_PLANNED_TO_ENROLL] [int] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	HEAP
)
GO