CREATE TABLE [CONSUMPTION_FINANCE].[FactAgingSAP] (
    [FactAgingSAPKey]      BIGINT           IDENTITY (1, 1) NOT NULL,
    [PostingDateKey]       INT              NULL,
    [NetDueDateKey]        INT              NULL,
    [CompanyKey]           INT              NULL,
    [CompanyCode]          NVARCHAR (4)     NULL,
    [FiscalYear]           NVARCHAR (4)     NULL,
    [DocuNumber]           NVARCHAR (10)    NULL,
    [LineItemNumber]       NVARCHAR (3)     NULL,
    [DocuType]             NVARCHAR (2)     NULL,
    [DocuStatus]           NVARCHAR (1)     NULL,
    [CurrencyKey]          NVARCHAR (5)     NULL,
    [LocalCurrencyKey]     NVARCHAR (5)     NULL,
    [SecondLocalCurrency]  NVARCHAR (5)     NULL,
    [DocuHeaderText]       NVARCHAR (25)    NULL,
    [PostingDate]          NVARCHAR (8)     NULL,
    [DocuDate]             NVARCHAR (8)     NULL,
    [PostingKey]           NVARCHAR (2)     NULL,
    [DebitCreditIndicator] NVARCHAR (1)     NULL,
    [AccountType]          NVARCHAR (1)     NULL,
    [BusinessAreaName]     NVARCHAR (4)     NULL,
    [DocuAmount]           DECIMAL (38, 18) NULL,
    [LocalAmount]          DECIMAL (38, 18) NULL,
    [SecondLocalAmount]    DECIMAL (38, 18) NULL,
    [AssignmentNumber]     NVARCHAR (18)    NULL,
    [ItemText]             NVARCHAR (50)    NULL,
    [OrderNumber]          NVARCHAR (12)    NULL,
    [GLAccount]            NVARCHAR (10)    NULL,
    [BaselineDate]         NVARCHAR (8)     NULL,
    [PaymentTermsKey]      NVARCHAR (4)     NULL,
    [TaxCode]              NVARCHAR (2)     NULL,
    [ValueDate]            NVARCHAR (8)     NULL,
    [SecondLocalAccount]   NVARCHAR (10)    NULL,
    [NetDueDate]           NVARCHAR (8)     NULL,
    [CustomerNumber]       NVARCHAR (10)    NULL,
    [CustomerCountryKey]   NVARCHAR (3)     NULL,
    [CustomerName]         NVARCHAR (35)    NULL,
    [CreatedBy]            VARCHAR (100)    NOT NULL,
    [UpdatedBy]            VARCHAR (100)    NOT NULL,
    [CreatedAt]            DATETIME         NOT NULL,
    [UpdatedAt]            DATETIME         NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

