CREATE TABLE [CONSUMPTION_PRIMAREPORTING].[Projects]
(
	[Project Code] [varchar](20) NULL,
	[Parent Project Code] [varchar](20) NULL,
	[Project Name] [varchar](255) NULL,
	[Protocol Title] [nvarchar](max) NULL,
	[Investigation Drug] [varchar](255) NULL,
	[Indication] [varchar](255) NULL,
	[Key Words] [varchar](1000) NULL,
	[Llt 1] [varchar](1000) NULL,
	[Pt 1] [varchar](1000) NULL,
	[Soc 1] [varchar](1000) NULL,
	[Llt 2] [varchar](1000) NULL,
	[Pt 2] [varchar](1000) NULL,
	[Soc 2] [varchar](1000) NULL,
	[Study Group] [varchar](255) NULL,
	[Drug Who Code Lvl 2] [varchar](1000) NULL,
	[Drug Who Code Lvl 4] [varchar](1000) NULL,
	[Study Therapy] [varchar](255) NULL,
	[Eudract] [varchar](50) NULL,
	[Ind] [varchar](20) NULL,
	[Dib Date] [datetime] NULL,
	[Sponsor ID] [int] NULL,
	[Is Direct] [bit] NULL,
	[Psi Client ID] [int] NULL,
	[Pm Coordinator ID] [int] NULL,
	[Pm ID] [int] NULL,
	[Supervisor ID] [int] NULL,
	[Psi Client Pm Id] [int] NULL,
	[Study Type ID] [int] NULL,
	[Object of Trial ID] [int] NULL,
	[Study Subject Population ID] [int] NULL,
	[Project Status ID] [int] NULL,
	[Old Project Status ID] [int] NULL,
	[Project Phase ID] [int] NULL,
	[Project Phase ID Manual] [int] NULL,
	[Project Phase ID Calc] [int] NULL,
	[Is on Hold] [bit] NULL,
	[Is Terminated] [bit] NULL,
	[Is Backup] [bit] NULL,
	[Project Deliverable] [varchar](500) NULL,
	[Project Deliverable ID] [int] NULL,
	[Development Phase ID] [int] NULL,
	[Therapeutic Area ID] [int] NULL,
	[Therapeutic Area ID 1] [int] NULL,
	[Therapeutic Area ID Sub 1] [int] NULL,
	[Therapeutic Area ID 2] [int] NULL,
	[Therapeutic Area ID Sub 2] [int] NULL,
	[Therapeutic Area ID 3] [int] NULL,
	[Therapeutic Area ID Sub 3] [int] NULL,
	[Acronym] [varchar](10) NULL,
	[Is Ind] [bit] NULL,
	[Is Central Lab] [int] NULL,
	[Planned Sites PSI] [int] NULL,
	[Planned Sites Global] [int] NULL,
	[Planned Subjects PSI] [int] NULL,
	[Planned Subjects Global] [int] NULL,
	[Start Date] [datetime] NULL,
	[Approval Date] [datetime] NULL,
	[Enrollment Completion Date] [datetime] NULL,
	[End Date] [datetime] NULL,
	[Through Account ID] [int] NULL,
	[Sites Comment] [nvarchar](2000) NULL,
	[Subjects Comment] [nvarchar](2000) NULL,
	[Services] [varchar](1000) NULL,
	[Currency] [varchar](100) NULL,
	[PSI Entity] [int] NULL,
	[Geomix Aggregate] [varchar](8000) NULL,
	[Services Aggregate] [varchar](8000) NULL,
	[Deliverable Aggregate] [varchar](8000) NULL,
	[Drugs Aggregate] [varchar](8000) NULL,
	[Non PSI Countries] [varchar](1000) NULL,
	[BD Comment] [nvarchar](max) NULL,
	[Comment] [nvarchar](max) NULL,
	[CRF Type] [int] NULL,
	[Indication Score] [int] NULL,
	[Monitoring Frequency E] [varchar](50) NULL,
	[Monitoring Frequency T] [varchar](50) NULL,
	[Monitoring Frequency F] [varchar](50) NULL,
	[Monitoring Frequency FLT] [varchar](50) NULL,
	[Monitoring Frequency UE] [varchar](50) NULL,
	[Monitoring Frequency UT] [varchar](50) NULL,
	[Monitoring Frequency UF] [varchar](50) NULL,
	[Monitoring Frequency UFLT] [varchar](50) NULL,
	[Unblinded Monitoring] [int] NULL,
	[Created By] [varchar](50) NULL,
	[Created At] [datetime] NULL,
	[Updated By] [varchar](50) NULL,
	[Updated At] [datetime] NULL,
	[Record Active] [int] NULL,
	[Row Version] [varchar](50) NULL,
	[Plannes Sites EU] [int] NULL,
	[Planned Subjects EU] [int] NULL,
	[Sponsor EU Legal Representative] [varchar](500) NULL,
	[Contract type] [int] NULL,
	[PSI Contracting Entity] [int] NULL,
	[Contract Currency] [int] NULL,
	[Rep Portal Flag] [bit] NULL,
	[Sponsor Partner ID] [int] NULL,
	[DM Project ID] [int] NULL,
	[Inflation Rate] [float] NULL,
	[Setup Months] [float] NULL,
	[Enrollment Months] [float] NULL,
	[Treatment Months] [float] NULL,
	[Closure Months] [float] NULL,
	[Passthrough Currency ID] [int] NULL,
	[Passthrough Src Doc Required] [int] NULL,
	[Project Folder Path] [varchar](255) NULL,
	[Purchase Order Number] [varchar](100) NULL,
	[Discount  Rate] [float] NULL,
	[Hourly Rates Version ID] [int] NULL,
	[Passthrough Is Data Loaded] [int] NULL,
	[Indication ID] [int] NULL,
	[Indication ID 2] [int] NULL,
	[Sub Indication ID] [int] NULL,
	[Sub Indication ID 2] [int] NULL,
	[Client Project Code] [varchar](255) NULL,
	[Contract Date] [datetime] NULL,
	[Passthrough Finalized] [int] NULL,
	[Is Test] [bit] NULL,
	[SAP Project Code] [int] NULL,
	[SAP Customer Number] [int] NULL,
	[Probability ID] [int] NULL,
	[Is Manual Probability] [bit] NULL,
	[Is Shelved] [int] NULL,
	[Invoiced BTRS] [int] NULL,
	[Is Transitioned] [bit] NULL,
	[Passthrough Budget] [decimal](18, 2) NULL,
	[Passthrough Threshold] [decimal](18, 2) NULL,
	[Ct Number] [varchar](20) NULL,
	[Replenish Amount] [int] NULL,
	[Replenish Comments] [varchar](1000) NULL,
	[Sponsor] [nvarchar](2000) NULL,
	[Study Phase ID Calc] [int] NULL,
	[Study Phase] [nvarchar](200) NULL,
	[Therapeutic Area] [nvarchar](200) NULL,
	[PM Coordinator] [varchar](102) NULL,
	[Status] [nvarchar](200) NULL,
	[Study Type] [nvarchar](200) NULL,
	[Geomix] [nvarchar](max) NULL,
	[Services Conception] [nvarchar](max) NULL,
	[PSI Entity Name] [nvarchar](200) NULL,
	[Start Date Planned] [datetime] NULL,
	[Start Date Planned Formatted] [datetime] NULL,
	[Start Date Actual] [datetime] NULL,
	[Start Date Actual Formattted] [datetime] NULL,
	[FPI Planned] [datetime] NULL,
	[FPI Actual] [datetime] NULL,
	[LPI Planned] [datetime] NULL,
	[LPI Actual] [datetime] NULL,
	[LPO Planned] [datetime] NULL,
	[LPO Actual] [datetime] NULL,
	[End Date Planned] [datetime] NULL,
	[End Date Planned Formatted] [datetime] NULL,
	[End Date Actual] [datetime] NULL,
	[End Date Actual Formatted] [datetime] NULL,
	[End Date Formatted] [datetime] NULL,
	[Ctms] [int] NULL,
	[Clinical Supplies] [bit] NULL,
	[Epfm] [bit] NULL,
	[Contract Study Type] [nvarchar](50) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	HEAP
)
GO