CREATE TABLE [CONSUMPTION_PRIMAREPORTING].[HrEmployeeContractHistory]
(
	[EmployeeId] [int] NULL,
	[ContractId] [int] NULL,
	[ContractHistoryStartDate] [date] NULL,
	[ContractHistoryEndDate] [date] NULL,
	[EmployeeFirstName] [varchar](50) NULL,
	[EmployeeLastName] [varchar](50) NULL,
	[EmployeeFullName] [varchar](102) NULL,
	[EmployeeWithPsiSince] [date] NULL,
	[EmployeeRecordStatus] [int] NULL,
	[EmployeeRecordStatusConception] [nvarchar](100) NULL,
	[PhoneNumber] [varchar](100) NULL,
	[PhoneExtention] [varchar](65) NULL,
	[MobilePhoneNumber] [varchar](100) NULL,
	[EmployeeOfficeCountryRegion] [int] NULL,
	[EmployeeOfficeCountryRegionName] [varchar](200) NULL,
	[OfficeId] [int] NULL,
	[OfficeCode] [varchar](20) NULL,
	[OfficeName] [varchar](30) NULL,
	[OfficeAddress] [varchar](255) NULL,
	[OfficeCity] [int] NULL,
	[OfficeCityCode] [varchar](20) NULL,
	[OfficeCityName] [varchar](100) NULL,
	[OfficeCountryId] [int] NULL,
	[OfficeCountryCode] [varchar](2) NULL,
	[OfficeCountryName] [varchar](100) NULL,
	[OfficeLocation] [varchar](250) NULL,
	[OfficeLocationTypeId] [int] NULL,
	[DepartmentId] [int] NULL,
	[DepartmentName] [varchar](100) NULL,
	[DepartmentShortName] [varchar](40) NULL,
	[DepartmentFullName] [varchar](208) NULL,
	[DepartmentLocation] [nvarchar](200) NULL,
	[DepartmentIsGroup] [bit] NULL,
	[DepartmentIsOperations] [bit] NULL,
	[PositionId] [int] NULL,
	[PositionName] [varchar](100) NULL,
	[PositionShortName] [varchar](50) NULL,
	[PositionLocation] [nvarchar](400) NULL,
	[PositionIsGroup] [bit] NULL,
	[BillableId] [int] NULL,
	[Billability] [nvarchar](200) NULL,
	[ContractExpiryDate] [date] NULL,
	[ContractClass] [int] NULL,
	[ContractClassType] [varchar](10) NULL,
	[ContractClassName] [nvarchar](200) NULL,
	[ContractTimeFrameId] [int] NULL,
	[ContractTimeFrameName] [nvarchar](200) NULL,
	[ContractPositionId] [int] NULL,
	[SecondaryPositionId] [int] NULL,
	[OfficeSuperviserId] [int] NULL,
	[PsiSupervisorId] [int] NULL,
	[FTE] [float] NULL,
	[ContractHoursPerWeek] [float] NULL,
	[CountryHoursPerWeek] [float] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO