CREATE TABLE [CONSUMPTION_PRIMAREPORTING].[Sites]
(
	[Project Code] [varchar](20) NULL,
	[Project Name] [varchar](255) NULL,
	[Not PSI Managed] [bit] NULL,
	[Country ID] [int] NULL,
	[Country] [varchar](100) NULL,
	[City ID] [int] NULL,
	[City] [varchar](100) NULL,
	[Site ID] [int] NULL,
	[Site Name] [varchar](500) NULL,
	[Site Name2] [varchar](255) NULL,
	[Site Full Name] [varchar](1000) NULL,
	[Site Address ID] [int] NULL,
	[Site Address] [nvarchar](1000) NULL,
	[PI Full Name] [nvarchar](204) NULL,
	[PI First Name] [nvarchar](100) NULL,
	[PI Last Name] [nvarchar](100) NULL,
	[Comments] [varchar](1000) NULL,
	[Site Status] [nvarchar](200) NULL,
	[Planned] [int] NULL,
	[Screened] [int] NULL,
	[Screened Out] [int] NULL,
	[Enrolled] [int] NULL,
	[In Screening] [int] NULL,
	[In Treatment] [int] NULL,
	[Discontinued Treatment] [int] NULL,
	[In Follow-Up] [int] NULL,
	[Discontinued Follow-Up] [int] NULL,
	[Completed] [int] NULL,
	[In Study] [int] NULL,
	[Discontinued] [int] NULL,
	[CTA Tracked] [varchar](3) NULL,
	[# Main CTAs Tracked] [int] NULL,
	[# Main CTAs Executed] [int] NULL,
	[All Main CTAs Executed] [varchar](3) NULL,
	[Site Evaluation Forecast Date] [datetime] NULL,
	[Site Evaluation Planned Date] [datetime] NULL,
	[Site Evaluation Date] [datetime] NULL,
	[Site Selection Forecast Date] [datetime] NULL,
	[Site Selection Planned Date] [datetime] NULL,
	[Site Selection Date] [datetime] NULL,
	[Site Activation Forecast Date] [datetime] NULL,
	[Site Activation Planned Date] [datetime] NULL,
	[Site Activation Date] [datetimeoffset](7) NULL,
	[LPI Actual Date (Country)] [datetime] NULL,
	[Site Closeout Forecase Date] [datetime] NULL,
	[Site Closeout Planned Date] [datetime] NULL,
	[Site Closeout Date] [datetime] NULL,
	[Months Active] [decimal](21, 7) NULL,
	[Ip-Red Approval Date] [date] NULL,
	[Ip-Red Approval Planned Date] [datetime] NULL,
	[Ip-Red Approval to Site Activation (Days)] [int] NULL,
	[IRB IEC Approval Date] [datetime] NULL,
	[Site Initiation Visit Date] [datetime] NULL,
	[Site Initiation Planned Visit Date] [datetime] NULL,
	[Site Initiation Forecast Visit Date] [datetime] NULL,
	[Site Initiation to Site Activation (Days)] [int] NULL,
	[First Subject Screened Date] [date] NULL,
	[Site Activation to First Screened (Days)] [int] NULL,
	[FPI Date] [datetime] NULL,
	[Site Activation to FPI (Days)] [int] NULL,
	[Site Activation Comments] [varchar](2000) NULL,
	[Site Ip-Red Approval Comments] [varchar](2000) NULL,
	[First Consent Date] [date] NULL,
	[First Screened Date] [date] NULL,
	[Site Cancelled Date] [date] NULL,
	[Enrollment Suspended Date] [date] NULL,
	[Enrollment Suspension Duration] [int] NULL,
	[Enrollment End Date] [datetime] NULL,
	[Screening Rate] [float] NULL,
	[Screenout Rate] [float] NULL,
	[Enrollment Rate] [float] NULL,
	[Dropout Rate] [float] NULL,
	[Screening Rate Calc] [decimal](38, 21) NULL,
	[Enrollment Rate Calc] [decimal](38, 21) NULL,
	[Screening Rate Planned] [float] NULL,
	[Screenout Rate Planned] [float] NULL,
	[Enrollment Rate Planned] [float] NULL,
	[Site Monitoring Frequency] [decimal](38, 2) NULL,
	[Source Server] [varchar](255) NULL,
	[Transitioned To Other CRO Date] [date] NULL,
	[Sponsor Comments] [varchar](1000) NULL,
	[OSF Type ID] [int] NULL,
	[Site Initiation Visit Survey Rate] [decimal](10, 2) NULL,
	[Close Out Visit Survey Rate] [decimal](10, 2) NULL,
	[Reporting Site ID] [varchar](255) NULL,
	[Ip-Red Approval to Site Activation (Business Days)] [int] NULL,
	[Site Initiation to Site Activation (Business Days)] [int] NULL,
	[Site approval date] [datetime] NULL,
	[Site approval to Site Activation (Days)] [int] NULL,
	[Site approval to Site Activation (Business Days)] [int] NULL,
	[Selection Visit date] [datetime] NULL,
	[Selection Visit to Site Activation (Days)] [int] NULL,
	[Selection Visit to Site Activation (Business Days)] [int] NULL,
	[RMV #2 (Date)] [datetime] NULL,
	[# PDs after RMV #2] [int] NULL,
	[RMV #1 Blinded (date)] [datetime] NULL,
	[RMV #1 Unblinded (date)] [datetime] NULL,
	[FPI to RMV #1 Blinded (Business days)] [int] NULL,
	[FPI to RMV #1 Unblinded (Business days)] [int] NULL,
	[First RMV on time (Blinded)] [varchar](3) NULL,
	[First RMV on time (Unblinded)] [varchar](3) NULL,
	[First RMV Overdue (Blinded)] [varchar](3) NULL,
	[First RMV Overdue (Unblinded)] [varchar](3) NULL,
	[Handed Over To Operations Date] [datetimeoffset](7) NULL,
	[Number Days Site ID Project Preparations] [int] NULL,
	[CDA Executed Date] [datetimeoffset](7) NULL,
	[CDA Sent Date] [datetimeoffset](7) NULL,
	[Number Days CDA Timelines] [int] NULL,
	[FQ SIQ Sent Date] [datetimeoffset](7) NULL,
	[FQ SIQ Received Date] [datetimeoffset](7) NULL,
	[Number Days SIQ Timelines] [int] NULL,
	[Number Days Site Identified Timelines Combine CDASIQ Timelines] [int] NULL,
	[Selection Visit Forecast Date] [datetimeoffset](7) NULL,
	[Number Days SSV Scheduled Timelines] [int] NULL,
	[Selection Date] [datetimeoffset](7) NULL,
	[Number Days Site Selected Timelines] [int] NULL,
	[Initiation Visit Date] [datetimeoffset](7) NULL,
	[Number Days Initiation Visit Timelines] [int] NULL,
	[Site Activation Event Date] [datetimeoffset](7) NULL,
	[Number Days Site Activation Timelines] [int] NULL,
	[Screening Date] [datetimeoffset](7) NULL,
	[Number Days First Patient Screened Timelines] [int] NULL,
	[Randomization Date] [datetimeoffset](7) NULL,
	[Enrollment Date] [datetimeoffset](7) NULL,
	[Number Days First Patient Enrolled Timelines] [int] NULL,
	[Number Days Site Selection To Activation] [int] NULL,
	[Account Name] [nvarchar](2000) NULL,
	[Account ID] [int] NULL,
	[SubAccount ID] [int] NULL,
	[Account ID 2] [int] NULL,
	[SubAccount ID 2] [int] NULL,
	[Account Contracted] [bit] NULL,
	[Account 2 Contracted] [bit] NULL,
	[RecordActive] [int] NULL,
	[Days since Activation] [int] NULL,
	[Non Screening (Expected Scr Rate)] [varchar](3) NULL,
	[Number Work Days Ipreds FirstSubmission To Approval Date] [int] NULL,
	[EhrSystemList] [varchar](200) NULL,
	[EhrSystemCustom] [varchar](250) NULL,
	[LocalEcApprovalRequiredId] [int] NULL,
	[RaLocalApprovalRequiredList] [int] NULL,
	[AdditionalReviewBoardId] [int] NULL,
	[AdditionalReviewBoardCustom] [varchar](250) NULL,
	[IsSatellite] [bit] NULL,
	[MainSiteId] [int] NULL,
	[SourceEssence] [varchar](30) NULL,
	[SourceObjectId] [int] NULL,
	[SpecializationId] [int] NULL,
	[Number Work Days Ipreds Submission To Approval Date] [int] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO