CREATE TABLE [CONSUMPTION_ClinOpsFinance].[EmployeeContractUtilization_Post]
(
	[CadenceBudget_LaborCost_PrimaUtilization_JuncKey] [bigint] NOT NULL,
	[EMPLOYEE_ID] [int] NOT NULL,
	[ContractId] [int] NOT NULL,
	[ContractHistoryStartDate] [date] NULL,
	[ContractHistoryEndDate] [date] NULL,
	[FULL_NAME] [varchar](102) NULL,
	[EmployeeCountryId] [int] NULL,
	[OFFICE_COUNTRY_NAME] [varchar](100) NULL,
	[DepartmentId] [int] NULL,
	[DEPARTMENT] [varchar](100) NULL,
	[POSITION_ID] [int] NULL,
	[POSITION] [varchar](100) NULL,
	[TIME_FRAME] [nvarchar](200) NULL,
	[FTE] [float] NULL,
	[BILLABLE_ID] [int] NULL,
	[BILLABILITY] [nvarchar](4000) NULL,
	[ContractHoursPerWeek] [float] NULL,
	[CountryHoursPerWeek] [float] NULL,
	[TsProjectCode] [nvarchar](80) NULL,
	[TsCountryId] [int] NULL,
	[TsTitle] [varchar](100) NULL,
	[TsPosition] [varchar](100) NULL,
	[isBillable] [varchar](3) NULL,
	[TitleOrPositionToUse] [varchar](100) NULL,
	[DurationInHours] [decimal](38, 6) NOT NULL,
	[DurationInMinutes] [int] NOT NULL,
	[NonBillableDurationInMinutes] [int] NOT NULL,
	[BillableDraftDurationInMinutes] [int] NOT NULL,
	[BillableSubmittedDurationInMinutes] [int] NOT NULL,
	[BillableApprovedDurationInMinutes] [int] NOT NULL,
	[IsHoliday] [int] NOT NULL,
	[IsVacation] [int] NOT NULL,
	[IsSickLeave] [numeric](10, 1) NOT NULL,
	[IsDayOff] [int] NOT NULL,
	[IsBusinessTrip] [int] NOT NULL,
	[IsWeekend] [int] NOT NULL,
	[IsDismiss] [int] NOT NULL,
	[Attendance] [varchar](38) NULL,
	[IsLongTermLeave] [int] NOT NULL,
	[Date] [date] NULL,
	[Year] [int] NULL,
	[Month] [int] NULL,
	[StartofMonth_Date] [date] NULL,
	[Date (Utilization)] [date] NULL,
	[Currency] [varchar](4) NOT NULL,
	[IsAbsent] [numeric](11, 1) NULL,
	[Hours Billed] [numeric](18, 6) NULL,
	[CadenceDepartmentName] [varchar](250) NULL,
	[ContractClassName] [nvarchar](200) NULL,
	[ContractClassType] [varchar](10) NULL,
	[Filter] [varchar](5) NOT NULL,
	[BomDateId] [int] NULL,
	[UtilizationDateId] [int] NULL,
	[Fridays] [int] NULL,
	[Hours Expected, Daily] [float] NULL
)
WITH
(
	DISTRIBUTION = HASH ( [EMPLOYEE_ID],[OFFICE_COUNTRY_NAME],[DEPARTMENT],[Year],[Month] ),
	CLUSTERED COLUMNSTORE INDEX
)
GO