CREATE TABLE [STAGING_CADENCE].[MonthlyTaskTaskCountry]
(
	[Period Year] [int] NULL,
	[Period Month] [int] NULL,
	[Project Name] [nvarchar](200) NULL,
	[Project Currency Code] [nvarchar](3) NULL,
	[Project Currency Name] [nvarchar](3) NULL,
	[Service] [nvarchar](200) NULL,
	[Task Code] [nvarchar](50) NULL,
	[Task Name] [nvarchar](200) NULL,
	[Task Country Name] [nvarchar](100) NULL,
	[Unit type] [nvarchar](200) NULL,
	[Part Order Index] [int] NULL,
	[Segment Order Index] [int] NULL,
	[Function Code] [nvarchar](50) NULL,
	[Function Name] [nvarchar](200) NULL,
	[Department] [nvarchar](200) NULL,
	[Function Country Name] [nvarchar](100) NULL,
	[Project Ref Id] [bigint] NULL,
	[Archived Project Ref Id] [bigint] NULL,
	[PRIMA Project Id] [nvarchar](100) NULL,
	[Project Status] [nvarchar](20) NULL,
	[Project Phase] [nvarchar](20) NULL,
	[Is Deleted Task] [bit] NULL,
	[SUM Function Reconciliation Approved Units] [decimal](19, 4) NULL,
	[Task Period CADENCE Earned Value] [decimal](19, 4) NULL,
	[Task Reconciliation CADENCE Earned Value] [decimal](19, 4) NULL,
	[Task CADENCE Earned Value] [decimal](19, 4) NULL,
	[Task CADENCE Planned Unit Cost] [decimal](19, 4) NULL,
	[SUM Function Period TimeSheet Actual Total Hours]  [decimal](19, 4) NULL,
	[SUM Task Period Approved Total Units] [decimal](19, 4) NULL,
	--[SUM Function TimeSheet Actual Total Hours] [decimal](19,4) NULL,
	[SUM Function Planned Total Cost Adjusted] [decimal](19,4) NULL,
	[SUM Function Planned Total Hours] [decimal](19,4) NULL,
	[Function CurrentRate Adjusted] [decimal](19,4) NULL,
	[SUM Task Planned Total Units] [decimal](19,4) NULL,
	--[SUM Task Period Approved Total Units] [decimal](19,4) NULL,
	[SUM Task Approved Total Units] [decimal](19,4) NULL,
	[RecordUpdateType] [varchar](3) NULL,
	[RecordCount] [int] NULL,
	[Total SUM Function TimeSheet Period Actual Total Hours] [decimal](19,4) NULL,
	--[Total SUM Function TimeSheet Actual Total Hours] [decimal](19,4) NULL,
	[Total SUM Function Planned Total Cost Adjusted] [decimal](19,4) NULL,
	[Total SUM Task Planned Total Units] [decimal](19,4) NULL,
	[Total SUM Function Planned Total Hours] [decimal](19,4) NULL,
	[Total SUM Task PEriod Approved Total Units] [decimal](19,4) NULL,
	[Calc Total Actual Total Hours (Allocated)] [decimal](19,4) NULL,
	[Actual Total Hours (Allocated)] [decimal](19,4) NULL,
	[Calc Earned Value (Budget)] [decimal](19,4) NULL,
	[Calc Total Earned Value (Budget)] [decimal](19,4) NULL,
	[Earned Value (50% Direct allocation)] [decimal](19,4) NULL,
	[Earned Value (Direct allocation) Version-2] [decimal](19,4) NULL,
	[Non-allocated Earned Value] [decimal](19,4) NULL,
	[Non-allocated Earned Value Version-2] [decimal](19,4) NULL,
	[Calc Total Non-allocated Earned Value] [decimal](19,4) NULL,
	[Calc Total Non-allocated Earned Value Version-2] [decimal](19,4) NULL,
	[SUM Function Period Actual Cost] [decimal](19,4) NULL,
	[SUM Function Reconciliation Actual Cost] [decimal](19,4) NULL,
	[SUM Function Actual Cost] [decimal](19,4) NULL,
	[Original Actual Total Hours (Allocated)] [decimal](19,4) NULL,
	[Calc SUM Function Period Actual Cost] [decimal](19,4) NULL,
	[Calc SUM Function Actual Cost] [decimal](19,4) NULL,
	[Actual Cost (Allocated)] [decimal](19,4) NULL,
	[Total Actual Cost (Allocated)] [decimal](19,4) NULL,
	[Calc Actual Cost (Allocated)] [decimal](19,4) NULL,
	[TS hours proportion] [decimal](19,8) NULL,
	[Actual Cost Proportion] [decimal](19,8) NULL,
	[Actual Cost (Allocated) Proportion] [decimal](19,8) NULL,
	[IsApprvedUnitLessThan10PercentPlannedUnits] [nvarchar](3) NULL,
	[Calculated Approved Units] [decimal](19,4) NULL,
	[Calculated Planned Units] [decimal](19,4) NULL,
	[Calculated Unit Cost] [decimal](19,4) NULL	
)
WITH
(
	DISTRIBUTION = HASH ( [Period Year],[Period Month],[Project Name],[Task Code],[Task Country Name],[Part Order Index],[Segment Order Index] ),
	CLUSTERED COLUMNSTORE INDEX
)
GO