CREATE TABLE [STAGING_CADENCE].[ReconciliationPopulation]
(
	[Period Year] [int] NOT NULL,
	[Period Month] [int] NOT NULL,
	[Data Period Year] [int] NULL,
	[Data Period Month] [int] NULL,
	[Project Name] [nvarchar](100) NULL,
	[Project Currency Code] [nvarchar](3) NULL,
	[Project Currency Name] [nvarchar](3) NULL,
	[Service] [nvarchar](255) NULL,
	[Task Code] [nvarchar](50) NULL,
	[Task Name] [nvarchar](255) NULL,
	[Part Order Index] [int] NULL,
	[Segment Order Index] [int] NULL,
	[Task Country Name] [nvarchar](255) NULL,
	[Function Code] [nvarchar](255) NULL,
	[Function Name] [nvarchar](255) NULL,
	[Function Country Name] [nvarchar](255) NULL,
	[Department] [nvarchar](255) NULL,
	[Unit type] [nvarchar](100) NULL,
	[RecordUpdateType] [nvarchar](255) NULL,
	[Project Ref Id] [bigint] NULL,
	[Archived Project Ref Id] [bigint] NULL,
	[PRIMA Project Id] [nvarchar](100) NULL,
	[Project Status] [nvarchar](20) NULL,
	[Project Phase] [nvarchar](20) NULL,
	[Is Deleted Task] [bit] NULL,
	[SUM Function Reconciliation Approved Units] [decimal](19, 4) NULL,
	[Task Period CADENCE Earned Value] [decimal](19, 4) NULL,
	[Task Reconciliation CADENCE Earned Value] [decimal](19, 4) NULL,
	[Task CADENCE Earned Value] [decimal](19, 4) NULL,
	[Task CADENCE Planned Unit Cost] [decimal](19, 4) NULL,
	[SUM Function Planned Total Cost Adjusted] [decimal](19, 4) NULL,
	[Function CurrentRate Adjusted] [decimal](19, 4) NULL,
	[SUM Task Planned Total Units] [decimal](19, 4) NULL,
	[SUM Task Approved Total Units] [decimal](19, 4) NULL,
	[SUM Function Reconciliation TimeSheet Actual Total Hours] [decimal](19, 4) NULL,
	[SUM Function Actual Hours] [decimal](19, 4) NULL,
	[SUM Function Reconciliation Actual Cost] [decimal](19, 4) NULL,
	[SUM Task Reconciliation Actual Cost] [decimal](19, 4) NULL,
	[SUM Function Actual Cost] [decimal](19, 4) NULL,
	[SUM Function Planned Total Hours] [decimal](19, 4) NULL,
	[IsApprvedUnitLessThan10PercentPlannedUnits] [nvarchar](3) NULL,
	[From Period] [date] NULL,
	[To Period] [date] NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH ( [Period Year],[Period Month],[Project Name],[Task Code],[Part Order Index],[Segment Order Index],[Task Country Name],[Function Code] ),
	CLUSTERED COLUMNSTORE INDEX
)
GO