CREATE TABLE [STAGING_CADENCE].[FinalCountryReallocateTS]
(
	[Period Year] [int] NULL,
	[Period Month] [int] NULL,
	[Project Name] [nvarchar](200) NULL,
	[Project Currency Code] [nvarchar](3) NULL,
	[Project Currency Name] [nvarchar](3) NULL,
	[Service] [nvarchar](200) NULL,
	[Task Code] [nvarchar](50) NULL,
	[Task Name] [nvarchar](200) NULL,
	[Task Country Name] [nvarchar](100) NULL,
	[Unit type] [nvarchar](200) NULL,
	[Part Order Index] [int] NULL,
	[Segment Order Index] [int] NULL,
	[Function Code] [nvarchar](50) NULL,
	[Function Name] [nvarchar](200) NULL,
	[Department] [nvarchar](200) NULL,
	[Function Country Name] [nvarchar](100) NULL,
	[Project Ref Id] [bigint] NULL,
	[Archived Project Ref Id] [bigint] NULL,
	[PRIMA Project Id] [nvarchar](100) NULL,
	[Project Status] [nvarchar](20) NULL,
	[Project Phase] [nvarchar](20) NULL,
	[Is Deleted Task] [bit] NULL,
	[SUM Function Reconciliation Approved Units] [decimal](19, 4) NULL,
	[Task Period CADENCE Earned Value] [decimal](19, 4) NULL,
	[Task Reconciliation CADENCE Earned Value] [decimal](19, 4) NULL,
	[Task CADENCE Earned Value] [decimal](19, 4) NULL,
	[Task CADENCE Planned Unit Cost] [decimal](19, 4) NULL,
	[SUM Function Period TimeSheet Actual Total Hours]  [decimal](19, 4) NULL,
	[SUM Task Period Approved Total Units] [decimal](19, 4) NULL,
	[SUM Function Planned Total Cost Adjusted] [decimal](19,4) NULL,
	[SUM Function Planned Total Hours] [decimal](19,4) NULL,
	[Function CurrentRate Adjusted] [decimal](19,4) NULL,
	[SUM Task Planned Total Units] [decimal](19,4) NULL,
	[SUM Task Approved Total Units] [decimal](19,4) NULL,
	[SUM Function TimeSheet Actual Total Hours CT] [decimal](19,4) NULL,
	[SUM Function TimeSheet Actual Total Hours NCT] [decimal](19,4) NULL,
	[RecordUpdateType] [varchar](3) NULL,
	[CountByRecordUpdateType] [int] NULL,
	[Actual Hours (re-allocated)] [decimal](19,4) NULL,
	[Actual Total Hours (Allocated)] [decimal](19,4) NULL,
	[SUM Function Period Actual Cost] [decimal](19,4) NULL,
	[SUM Function Reconciliation Actual Cost] [decimal](19,4) NULL,
	[SUM Function Actual Cost] [decimal](19,4) NULL,
	[SUM Function Actual Cost CT] [decimal](19,4) NULL,
	[SUM Function Actual Cost NCT] [decimal](19,4) NULL,
	[Actual Cost (re-allocated)] [decimal](19,4) NULL,
	[Actual Cost (Allocated)] [decimal](19,4) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [Period Year],[Period Month],[Project Name],[Task Code],[Task Country Name],[Part Order Index],[Function Code],[Function Country Name] ),
	CLUSTERED COLUMNSTORE INDEX
)
GO