CREATE TABLE [STAGING_CADENCE].[CadenceExtractFunctionLocation]
(
	[Project ref Id] [bigint] NULL,
	[Project Name] [nvarchar](100) NULL,
	[Opportunity Id] [nvarchar](100) NULL,
	[Archived project ref Id] [bigint] NULL,
	[PRIMA Project Id] [nvarchar](100) NULL,
	[Project Status] [nvarchar](20) NULL,
	[Project Phase] [nvarchar](20) NULL,
	[Project Currency Code] [nvarchar](3) NULL,
	[Project Currency Name] [nvarchar](3) NULL,
	[CHF Contract Exchange Rate] [decimal](19,4) NULL,
	[USD Contract Exchange Rate] [decimal](19,4) NULL,
	[EUR Contract Exchange Rate] [decimal](19,4) NULL,
	[GBP Contract Exchange Rate] [decimal](19,4) NULL,
	[Period Name] [nvarchar](20) NULL,
	[Period Year] [int] NULL,
	[Period Month] [int] NULL,
	[Is Closed Period] [bit] NULL,
	[Service code] [nvarchar](50) NULL,
	[Service Name] [nvarchar](100) NULL,
	[Department Id] [bigint] NULL,
	[Department Name] [nvarchar](100) NULL,
	[Task Code] [nvarchar](50) NULL,
	[Task Name] [nvarchar](100) NULL,
	[Tracking Task Code] [nvarchar](50) NULL,
	[Tracking Task Name] [nvarchar](100) NULL,
	[Is Deleted Task] [bit] NULL,
	[Part Name] [nvarchar](100) NULL,
	[Part Order Index] [int] NULL,
	[Segment Order Index] [int] NULL,
	[Task Country Code] [nvarchar](50) NULL,
	[Task Country Name] [nvarchar](50) NULL,
	[Task Region Code] [nvarchar](50) NULL,
	[Task Region Name] [nvarchar](50) NULL,
	[Function Code] [nvarchar](50) NULL,
	[Function Name] [nvarchar](100) NULL,
	[Function Location Code] [nvarchar](50) NULL,
	[Function Location Name] [nvarchar](50) NULL,
	[Function Region Code] [nvarchar](50) NULL,
	[Function Region Name] [nvarchar](50) NULL,
	[Actual Hours] [decimal](19,4) NULL,
	[Rate] [decimal](19,4) NULL,
	[Planned Total Cost] [decimal](19,4) NULL,
	[Planned Total Hours] [decimal](19,4) NULL,
	[Reconciliation Actual Hours] [decimal](19,4) NULL,
	[Reconciliation Actual Cost] [decimal](19,4) NULL,
	[Period Actual Hours] [decimal](19,4) NULL,
	[Period Actual Cost] [decimal](19,4) NULL,
	[Actual Cost] [decimal](19,4) NULL,
	[Reconciliation Approved Units] [decimal](19, 4) NULL,
	[Reconciliation CADENCE Earned Value] [decimal](19, 4) NULL,
	[Layer] [nvarchar](50) NULL,
	[CREATED_AT] [datetime] NOT NULL,
	[UPDATED_AT] [datetime] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH ( [Project Name],[Period Year],[Period Month],[Task Code],[Part Order Index],[Segment Order Index],[Task Country Code] ),
	CLUSTERED COLUMNSTORE INDEX
)
GO