CREATE VIEW [CONSUMPTION_ClinOpsFinance].[Billability]
AS SELECT CAST(0 AS INT) AS BILLABLE_ID, CAST ('Fully Billable (85-100%)' as NVARCHAR(200)) AS 	BILLABILITY
UNION 
SELECT CAST(1 AS INT) AS BILLABLE_ID, CAST ('Partially billable (31-85%)' as NVARCHAR(200)) AS 	BILLABILITY
UNION 
SELECT CAST(2 AS INT) AS BILLABLE_ID, CAST ('Non-billable (0-30%)' as NVARCHAR(200)) AS 	BILLABILITY;
GO

